### ISSUE TITLE
Schedule interview with Clinton - Mobile developer

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Day-to-day#14]

**Comment by anujkhurana** [comment]
When is this scheduled for?

**Comment by Tanvi-HR** [comment]
Scheduled on Wednesday, 14th January at 6:00 pm.

**Comment by anujkhurana** [comment]
Can you please send out a meeting request for 6.00 P.M to suraj and me.
That ways it will be in our calendar and we will get reminded by google.
This should be done for every meeting/interview etc.
