### ISSUE TITLE
Get quotes for Air Conditioners 

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Day-to-day#34]

**Comment by Tanvi-HR** [comment]
LG - Essential Electronics
Contact Person: Mark / 9552926876, Rs.500 for site inspection (refundable after purchase) 
Approx. cost- 2 Tonne, 2 Star Rs40,500 (installation and stabilizer) 3 Star Rs. 1000 extra

Blue Star - Comfort Engineering
Contact Person: Rohan / 9822486899 
Approx. Cost- 2 Tonne, 2 Star Rs. 48000; 3 Star Rs. 2500 extra

**Comment by Tanvi-HR** [comment]
They want to visit the place before suggesting tonnage requirement and quoting final price.

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=0B17ClWYMGibaflV2QUgzMlBwRlJYVTRjbDhSazB3OVlGMG1yaFVfSk9LclFsY3ZXRDRISzA&authuser=0

Pls refer the above folder for quotations. Updated with quotation from Hitachi.

**Comment by anujkhurana** [comment]
Can we try the following:

Ask the following brands for their quote (we can find the authorized seller
by checking the brands website and finding local dealers)


   - Bluestar - i am being told for office use we should use them only.
   - O general
   - Hitachi
   - Lloyds - i think they will be cheaper.
   - Samsung
   - LG
   - We don't need all of the above. Let's get atleast 1 high end, 1 mid
   range and one 1 low end.


We need a quote for

   - 2 ton. Qty 2. Minimum 3 star rating. If with 4 or 5 star then that
   works too. the list here says there are lot of 5 star options available.
   https://www.bijlibachao.com/air-conditioners/comparison-of-various-brands-of-air-conditioners-on-bee-star-rating-in-india.html
      - If there are different 2 ton models by same brand then we will like
      to know our options.
   - 2.5/3 ton if available. Qty. 1
      - If there are different 2./3 ton models by same brand then we will
      like to know our options.
   - Installation and fitting.
   - AMC with 3 services a year.
   - Payment terms (advance/on completion).
   - Availability of stock and if we place order by Feb 2nd how soon can
   they finish installation.

Once we have a spreadsheet with all this data for all the sellers let's
take a decision.

To understand how to buy ac
http://www.indiahometips.com/buying-split-ac.html

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=0B17ClWYMGibaflV2QUgzMlBwRlJYVTRjbDhSazB3OVlGMG1yaFVfSk9LclFsY3ZXRDRISzA&authuser=0

Quotations by LG, Hitachi and Bluestar. Awaiting quotations from Llyod, O General and Samsung.

**Comment by anujkhurana** [comment]
Bluestar document only has the first page. The quote is not there.

**Comment by Tanvi-HR** [comment]
It can be viewed only in word.. has some excel hyperlink. I'll convert and upload.

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=1sJgmYU0sKQp7JDyVzYwQSPmFMwm-HuZPKdtZHm_L5ws&authuser=0

Pls refer this link for bluestar quote

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=1FaDEDBn2Sm4O2lad29_1hgeb2bQ8fl3szNIh3vY9sxo&authuser=0

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=1sJgmYU0sKQp7JDyVzYwQSPmFMwm-HuZPKdtZHm_L5ws&authuser=0

New quote from Bluestar - Pls refer Page 2.
