### ISSUE TITLE
Get quotes for glass partition 

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Day-to-day#35]

**Comment by Tanvi-HR** [comment]
How many partitions do we need?

**Comment by avantih** [comment]
Two. May be 3.

**Comment by Tanvi-HR** [comment]
![1](https://cloud.githubusercontent.com/assets/10397852/5953268/e4713d6e-a7ac-11e4-82a7-68c62bb37f2c.PNG)

Have a look at this layout

**Comment by Tanvi-HR** [comment]
Cost estimate given by a friend for cabins. 

Approx. Rs.240 per sqft. Amount will vary as per material used and dimensions.
