### ISSUE TITLE
Quotes for Internet Line 

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Day-to-day#41]
1. ethernet express quote for internet connection.
2. gwave internet connection
3. bsnl phone line

get both quotes consumer plan with limited bandwidth ...this we can get from their website only or they will have standard plans
for leased line ask for quote for 1 mbps and 2 mbps
we currently have 3 mbps with hathway
we can split it between hathway and other provider
or we can keep hathway at 3 and add backup as consumer plan
1:4 is fine for us

**Comment by anujkhurana** [comment]
Hathway 3MBPS 1:4 contention ratio = Rs. 7500/- (leased line).

**Comment by Tanvi-HR** [comment]
Tata doesn't have feasibility in Panjim Community Center. Tata showroom used to use a line but that is damaged and unusable. Installing new line will cost almost 2 lakh investment for the company. Only if we take 3 or 4 mbps line, they will have the cable and system up for us. 

They will be sending the quote for the same.

**Comment by Tanvi-HR** [comment]
Same with Tata, they do not give consumer plans to offices. They have sent a quote, pls check. 

Have also forwarded Gwave quote for 1:4.

**Comment by anujkhurana** [comment]
Since Hathway at 1:4 gives us best rates (7500/-). I think we will stick to
them for the 3MBPS line and add BSNL as backup (regular broadband).

Can you go back to Gwave and say we will take their 4 MBPS 1: 4 ratio if
they can reduce price to Rs. 7500/-

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=0B17ClWYMGibaSVhGS3M2UGtSdkVhdFdSeTU4Nk42SHlqS1Zv&authuser=0

Ethernet xpress doesn't provide 1:4, only 1:1 & 1:2. This quote is for 1:1, they'll send quote for 1:2 in some time.

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=0B17ClWYMGibaRTNsZUdwbEUtQ0pld3AxMXNfLUxrbXdRMFo0&authuser=0

Quote for 1:2 - 2mbps, 3mbps & 4 mbps, difference is 2k, 3.5k and 3k respectively.
