### ISSUE TITLE
Bank account opening - HDFC

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Day-to-day#43]

**Comment by Tanvi-HR** [comment]
Documents required

1. Memorandum of Association. -- 
2. Articles of Association --
3. certificate of incorporation. -- 
4.Pan Card of Company. -- Yes
5 Address proof and Pan card of directors. --  
6. A Cheque of Existing bank account. -- Yes
7. The following documents on the head. -- As per formats given by the bank

https://drive.google.com/open?id=0B17ClWYMGibaU3J2QkdpeEZ3SUE&authuser=0 

        a. board resolution 
        b. List of director. 
        c. Profit and loss sharing ratio 
        d. Annexure I

**Comment by anujkhurana** [comment]
Nice job done!
