### ISSUE TITLE
Get following banks to give proposals for handling our company account and salary accounts

### ISSUE THREAD

**Issue by anujkhurana** [ajency/Day-to-day#8]
HDFC
Kotak
Yes

**Comment by anujkhurana** [comment]
idbi

**Comment by Tanvi-HR** [comment]
Called Yes Bank and asked for proposal.

**Comment by Tanvi-HR** [comment]
https://drive.google.com/open?id=0B17ClWYMGibaMEZ0T1FpRG9TNk0&authuser=0

Folder containing proposals

**Comment by Tanvi-HR** [comment]
Folder updated with IDBI proposal

**Comment by Tanvi-HR** [comment]
Folder updated with HDFC proposal
